os: linux
dist: focal
language: node_js
node_js:
  - "12"
cache: npm

install: npm i && npm i --save-dev jsdoc
before_script: chmod +x ./demo/copy
script:
  - npm test

stages:
  - name: browser_stack
    if: branch = master OR tag IS present

jobs:
  include:
    - os: linux
    - os: osx
    - os: windows
      before_script: echo "Nothing to do"
      script:
        - npm run test:win

    - stage: browser_stack
      env:
        - BROWSERSTACK_USERNAME=$BROWSERSTACK_USERNAME
        - BROWSERSTACK_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY
        - PORT=3001
      after_success:
        - npm run bs
        - npm run bs:safari
        - npm run bs:android
        - npm run bs:ios
