name: Build Docs
on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up node env
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Cache modules
      uses: actions/cache@v2
      id: restore-cache
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-
    - name: Install dependencies
      if: steps.restore-cache.outputs.cache-hit != 'true'
      run: npm i && npm i --save-dev jsdoc
    - name: Set file perms on dev script
      if: ${{ !startsWith(runner.os, 'windows') }}
      run: chmod +x ./demo/copy
    - name: Build docs with custom options
      if: ${{ !startsWith(runner.os, 'windows') }}
      run: npm test
    - name: Build docs on Windows
      if: ${{ startsWith(runner.os, 'windows') }}
      run: npm run test:win
      shell: cmd
