name: Chrome on Android, Safari on iOS
on:
  push:
    branches:
      - develop
      - '!dependabot/**'
  pull_request_target:
    types: [opened, edited, reopened]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Set up BrowserStack env
      uses: browserstack/github-actions/setup-env@master
      with:
        username:  ${{ secrets.BROWSERSTACK_USERNAME }}
        access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
    - name: Start BrowserStackLocal Tunnel
      uses: browserstack/github-actions/setup-local@master
      with:
        local-testing: start
        local-logging-level: false
        local-identifier: random
    - uses: actions/checkout@v2
    - name: Set up node env
      uses: actions/setup-node@v2.1.5
      with:
        node-version: '15.x'
    - name: Cache modules
      uses: actions/cache@v2.1.6
      id: restore-cache
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-
    - name: Install dependencies
      run: npm i && npm i --save-dev jsdoc
    - name: Set file perms on dev script
      run: chmod +x ./demo/clean
    - name: Build docs
      run: npm test
    - name: Run Selenium tests
      env:
        BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
        BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        PORT: 8099
      run: |
        npm run bs:android
        npm run bs:ios
    - name: Stop BrowserStackLocal
      uses: browserstack/github-actions/setup-local@master
      with:
        local-testing: stop